# Generated by Django 5.1.1 on 2024-10-01 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoties',
            new_name='Categories',
        ),
    ]
