# Generated by Django 5.1.1 on 2024-10-01 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 1, 19, 16, 12, 651228), verbose_name='Дата'),
        ),
    ]
