# Generated by Django 5.1.1 on 2024-10-01 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_questions_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='dates',
        ),
        migrations.AddField(
            model_name='questions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 1, 19, 19, 15, 360099), verbose_name='Дата'),
        ),
    ]
