# Generated by Django 5.1.1 on 2024-10-02 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_questions_dates_questions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 2, 15, 13, 3, 59355), verbose_name='Дата'),
        ),
    ]
