# Generated by Django 5.1.1 on 2024-10-20 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_questions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 21, 1, 52, 59, 10763), verbose_name='Дата'),
        ),
    ]
