# Generated by Django 5.1.1 on 2024-10-02 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_questions_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='out_answer',
            field=models.BooleanField(default=False, verbose_name='Без ответа'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 2, 15, 54, 3, 2363), verbose_name='Дата'),
        ),
    ]
