# Generated by Django 5.1.1 on 2024-10-02 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_questions_out_answer_alter_questions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 2, 15, 58, 14, 709165), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='out_answer',
            field=models.BooleanField(default=True, verbose_name='Без ответа'),
        ),
    ]
