# Generated by Django 5.1.1 on 2024-10-03 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_questions_date_alter_questions_out_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 3, 16, 25, 41, 227596), verbose_name='Дата'),
        ),
    ]
