# Generated by Django 5.1.1 on 2024-10-03 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_questions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 3, 16, 41, 6, 63881), verbose_name='Дата'),
        ),
    ]
